import { nanoid } from "nanoid";

export const items = [
  {
    id: nanoid(),
    name: "Big Mac",
    price: 2,
    image: "big-mac.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Flip Flops",
    price: 3,
    image: "flip-flops.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Coca-Cola Pack",
    price: 5,
    image: "coca-cola-pack.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Movie Ticket",
    price: 12,
    image: "movie-ticket.jpg",
    countInCart: 0,
  },
  { id: nanoid(), name: "Book", price: 15, image: "book.jpg", countInCart: 0 },
  {
    id: nanoid(),
    name: "Lobster Dinner",
    price: 45,
    image: "lobster-dinner.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Video Game",
    price: 60,
    image: "video-game.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Amazon Echo",
    price: 99,
    image: "amazon-echo.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Year of Netflix",
    price: 100,
    image: "year-of-netflix.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Air Jordans",
    price: 125,
    image: "air-jordans.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Airpods",
    price: 199,
    image: "airpods.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Gaming Console",
    price: 299,
    image: "gaming-console.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Drone",
    price: 350,
    image: "drone.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Smartphone",
    price: 699,
    image: "smartphone.jpg",
    countInCart: 0,
  },
  { id: nanoid(), name: "Bike", price: 800, image: "bike.jpg", countInCart: 0 },
  {
    id: nanoid(),
    name: "Horse",
    price: 2500,
    image: "horse.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Acre of Farmland",
    price: 3000,
    image: "acre-of-farmland.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Designer Handbag",
    price: 5500,
    image: "designer-handbag.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Hot Tub",
    price: 6000,
    image: "hot-tub.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Diamond Ring",
    price: 10000,
    image: "diamond-ring.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Jet Ski",
    price: 12000,
    image: "jet-ski.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Rolex",
    price: 15000,
    image: "rolex.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Ford F-150",
    price: 30000,
    image: "ford-f-150.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Tesla",
    price: 75000,
    image: "tesla.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Monster Truck",
    price: 150000,
    image: "monster-truck.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Ferrari",
    price: 250000,
    image: "ferrari.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "McDonalds Franchise",
    price: 1500000,
    image: "mcdonalds-franchise.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Superbowl Ad",
    price: 5250000,
    image: "superbowl-ad.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Yacht",
    price: 7500000,
    image: "yacht.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "M1 Abrams",
    price: 8000000,
    image: "m1-abrams.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Formula 1 Car",
    price: 15000000,
    image: "formula-1-car.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Apache Helicopter",
    price: 31000000,
    image: "apache-helicopter.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Mansion",
    price: 45000000,
    image: "mansion.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Make a Movie",
    price: 100000000,
    image: "make-a-movie.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Boeing 747",
    price: 148000000,
    image: "boeing-747.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Mona Lisa",
    price: 780000000,
    image: "mona-lisa.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Skyscraper",
    price: 850000000,
    image: "skyscraper.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "Cruise Ship",
    price: 930000000,
    image: "cruise-ship.jpg",
    countInCart: 0,
  },
  {
    id: nanoid(),
    name: "NBA Team",
    price: 2120000000,
    image: "nba-team.jpg",
    countInCart: 0,
  },
];
